version: '3'

services:

   app:
      build: .
      image: overland-backend
      links:
        - db
      ports:
        - "5000:5000"
      volumes:
        - ./src:/app/.
      restart: always

   db:
      image: mysql:8
      environment:
        MYSQL_PASSWORD: "pepeloquito!"
        MYSQL_USER: "root"
      ports:
        - "3306:3306"