version: '2'

services:

   app:
      build: .
      image: overland-backend
      links:
        - db
      ports:
        - "5000:5000"
      volumes:
        - ./src:/app/.
      restart: always

   db:
      image: mysql:8
      ports:
        - "3306:3306"
      environment:
        MYSQL_PASSWORD: pepeloquito!
        MYSQL_USER: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
      restart: unless-stopped
      container_name: mysql-overland