"""empty message

Revision ID: 08861b6d95d3
Revises: ef9e6deb558f
Create Date: 2022-07-20 18:32:40.375291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08861b6d95d3'
down_revision = 'ef9e6deb558f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompanist', sa.Column('data_id', sa.Integer(), nullable=False))
    op.drop_constraint('accompanist_ibfk_1', 'accompanist', type_='foreignkey')
    op.create_foreign_key(None, 'accompanist', 'data', ['data_id'], ['id_data'], ondelete='CASCADE')
    op.drop_column('accompanist', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompanist', sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accompanist', type_='foreignkey')
    op.create_foreign_key('accompanist_ibfk_1', 'accompanist', 'client', ['client_id'], ['id_client'], ondelete='CASCADE')
    op.drop_column('accompanist', 'data_id')
    # ### end Alembic commands ###
