"""empty message

Revision ID: 0d32828b507b
Revises: 08861b6d95d3
Create Date: 2022-07-20 18:35:02.244755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d32828b507b'
down_revision = '08861b6d95d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accompanist_ibfk_1', 'accompanist', type_='foreignkey')
    op.drop_column('accompanist', 'data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompanist', sa.Column('data_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('accompanist_ibfk_1', 'accompanist', 'data', ['data_id'], ['id_data'], ondelete='CASCADE')
    # ### end Alembic commands ###
