"""empty message

Revision ID: 9d8256b5da41
Revises: 
Create Date: 2022-07-20 17:30:18.663450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8256b5da41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('accompanist_id', sa.Integer(), nullable=False))
    op.add_column('client', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.add_column('client', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('client', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'accompanist', ['accompanist_id'], ['id_accompanist'])
    op.create_foreign_key(None, 'client', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client', 'vehicle', ['vehicle_id'], ['id_vehicle'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client', 'hotel', ['hotel_id'], ['id_hotel'], ondelete='CASCADE')
    op.add_column('data', sa.Column('client_rol_id', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('gender_id', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('pathologies', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('nationality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data', 'pathologies', ['pathologies'], ['id_pathologies'], ondelete='CASCADE')
    op.create_foreign_key(None, 'data', 'gender', ['gender_id'], ['id_gender'], ondelete='CASCADE')
    op.create_foreign_key(None, 'data', 'nationality', ['nationality_id'], ['id_nationality'], ondelete='CASCADE')
    op.create_foreign_key(None, 'data', 'client', ['client_rol_id'], ['id_client'], ondelete='CASCADE')
    op.add_column('hotel', sa.Column('rooms_id', sa.Integer(), nullable=False))
    op.add_column('hotel', sa.Column('lunch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hotel', 'rooms', ['rooms_id'], ['id_rooms'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hotel', 'lunch', ['lunch_id'], ['id_lunch'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'lunch_id')
    op.drop_column('hotel', 'rooms_id')
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'nationality_id')
    op.drop_column('data', 'pathologies')
    op.drop_column('data', 'gender_id')
    op.drop_column('data', 'client_rol_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'hotel_id')
    op.drop_column('client', 'role_id')
    op.drop_column('client', 'vehicle_id')
    op.drop_column('client', 'accompanist_id')
    # ### end Alembic commands ###
