"""empty message

Revision ID: acf87483d385
Revises: 0d32828b507b
Create Date: 2022-07-20 18:37:21.698486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf87483d385'
down_revision = '0d32828b507b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompanist', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('accompanist', sa.Column('data_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accompanist', 'data', ['data_id'], ['id_data'], ondelete='CASCADE')
    op.create_foreign_key(None, 'accompanist', 'client', ['client_id'], ['id_client'], ondelete='CASCADE')
    op.add_column('client', sa.Column('data_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'data', ['data_id'], ['id_data'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'data_id')
    op.drop_constraint(None, 'accompanist', type_='foreignkey')
    op.drop_constraint(None, 'accompanist', type_='foreignkey')
    op.drop_column('accompanist', 'data_id')
    op.drop_column('accompanist', 'client_id')
    # ### end Alembic commands ###
