"""empty message

Revision ID: ef9e6deb558f
Revises: b36f6118fe7d
Create Date: 2022-07-20 18:32:02.281211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef9e6deb558f'
down_revision = 'b36f6118fe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accompanist', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accompanist', 'client', ['client_id'], ['id_client'], ondelete='CASCADE')
    op.drop_constraint('client_ibfk_5', 'client', type_='foreignkey')
    op.drop_column('client', 'data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('data_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_ibfk_5', 'client', 'data', ['data_id'], ['id_data'], ondelete='CASCADE')
    op.drop_constraint(None, 'accompanist', type_='foreignkey')
    op.drop_column('accompanist', 'client_id')
    # ### end Alembic commands ###
